angular.module('LuckyMall.controllers')
 .controller('HomeCtrl',function($scope,HomeSer){
    $scope.loadingToday=true;
     HomeSer.requestBannerData(function(response,status){
         if(status==1){
             $scope.data_banner=HomeSer.getData().banner;
             $scope.bannerReady=true;
             $scope.$broadcast('bannerReady');
         }else{
             $scope.bannerReady=true;
         }
     });
    HomeSer.requestTodayData(function(){
       $scope.loadingToday=false;
       $scope.data_todayList=HomeSer.getTodayData();
       $scope.ready=true;
    });
});
